web-server:
  image: almanac/web-server:production
  ports:
   - 80:3000
  links:
   - app-service
   - data-cache

app-service:
  image: almanac/app-service:production
  links:
   - data-cache

data-cache:
  image: redis
  volumes_from:
    - cachedb
  command: redis-server --appendonly yes
